//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmgSistemas.ControleFinanceiro.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGCF_REGISTRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AGCF_REGISTRO()
        {
            this.AGCF_REGISTRO1 = new HashSet<AGCF_REGISTRO>();
        }
    
        public string IDREGISTRO { get; set; }
        public string IDUSUARIO { get; set; }
        public string IDFONTES { get; set; }
        public string IDTIPOREGISTRO { get; set; }
        public string IDINTEGRANTE { get; set; }
        public string DESREGISTRO { get; set; }
        public string OBSDETALHES { get; set; }
        public bool BOLQUITADO { get; set; }
        public Nullable<int> NELPARCELA { get; set; }
        public Nullable<int> NELPARCELAFINAL { get; set; }
        public System.DateTime DTHDATAREGISTRO { get; set; }
        public System.DateTime DTHCOMPRA { get; set; }
        public decimal NUMVALOR { get; set; }
        public string IDREGISTROPAI { get; set; }
        public string CODMES { get; set; }
        public string CODANO { get; set; }
        public Nullable<bool> BOLPAGO { get; set; }
    
        public virtual AGCF_FONTES AGCF_FONTES { get; set; }
        public virtual AGCF_INTEGRANTES AGCF_INTEGRANTES { get; set; }
        public virtual AGCF_TIPOREGISTRO AGCF_TIPOREGISTRO { get; set; }
        public virtual AGCF_USUARIO AGCF_USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGCF_REGISTRO> AGCF_REGISTRO1 { get; set; }
        public virtual AGCF_REGISTRO AGCF_REGISTRO2 { get; set; }
    }
}
