//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmgSistemas.ControleFinanceiro.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGCF_USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AGCF_USUARIO()
        {
            this.AGCF_INTEGRANTES = new HashSet<AGCF_INTEGRANTES>();
            this.AGCF_FONTES = new HashSet<AGCF_FONTES>();
            this.AGCF_TIPOREGISTRO = new HashSet<AGCF_TIPOREGISTRO>();
            this.AGCF_REGISTRO = new HashSet<AGCF_REGISTRO>();
        }
    
        public string IDUSUARIO { get; set; }
        public string DESNOME { get; set; }
        public string DESLOGIN { get; set; }
        public string DESSENHA { get; set; }
        public string DESEMAIL { get; set; }
        public string DESTELEFONE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGCF_INTEGRANTES> AGCF_INTEGRANTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGCF_FONTES> AGCF_FONTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGCF_TIPOREGISTRO> AGCF_TIPOREGISTRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGCF_REGISTRO> AGCF_REGISTRO { get; set; }
    }
}
