//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmgSistemas.ControleFinanceiro.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGCF_FONTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AGCF_FONTES()
        {
            this.AGCF_REGISTRO = new HashSet<AGCF_REGISTRO>();
        }
    
        public string IDFONTES { get; set; }
        public string IDUSUARIO { get; set; }
        public string CODTIPOFONTE { get; set; }
        public string DESNOME { get; set; }
        public Nullable<int> NELDIAFECHAMENTO { get; set; }
        public Nullable<bool> BOLCARTAOCREDITO { get; set; }
        public string CODFONTE { get; set; }
    
        public virtual AGCF_USUARIO AGCF_USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGCF_REGISTRO> AGCF_REGISTRO { get; set; }
    }
}
