//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmgSistemas.ControleFinanceiro.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IGERENCEEntities : DbContext
    {
        public IGERENCEEntities()
            : base("name=IGERENCEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AGCF_INTEGRANTES> AGCF_INTEGRANTES { get; set; }
        public virtual DbSet<AGCF_USUARIO> AGCF_USUARIO { get; set; }
        public virtual DbSet<AGCF_FONTES> AGCF_FONTES { get; set; }
        public virtual DbSet<AGCF_TIPOREGISTRO> AGCF_TIPOREGISTRO { get; set; }
        public virtual DbSet<AGCF_REGISTRO> AGCF_REGISTRO { get; set; }
    }
}
